version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: ../docker/api.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - minio
  worker:
    build:
      context: ./worker
      dockerfile: ../docker/worker.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - minio
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: killfile
      POSTGRES_USER: killuser
      POSTGRES_PASSWORD: killpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: