version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: killfile-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - redis
      - minio
    volumes:
      - ./data/uploads:/app/uploads

  worker:
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    container_name: killfile-worker
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
      - OCR_ENABLED=true
    depends_on:
      - redis
      - minio

  redis:
    image: redis:7-alpine
    container_name: killfile-redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: killfile-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

  postgres:
    image: postgres:15-alpine
    container_name: killfile-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: killfile
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"