services:
  - type: web
    name: kill-file-api
    env: docker
    plan: starter
    dockerfilePath: ./api/Dockerfile # <-- check this path!
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: MINIO_ENDPOINT
        value: http://minio:9000
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
      - key: MINIO_BUCKET
        value: uploads
    port: 8080

  - type: worker
    name: kill-file-worker
    env: docker
    plan: starter
    dockerfilePath: ./worker/Dockerfile # <-- check this path!
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: MINIO_ENDPOINT
        value: http://minio:9000
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
      - key: MINIO_BUCKET
        value: uploads

  - type: pserv
    name: minio
    env: docker
    plan: starter
    image: minio/minio:latest # <-- Use official image!
    startCommand: server /data
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
    disks:
      - name: miniodata
        mountPath: /data
        sizeGB: 10
    port: 9000

  - type: pserv
    name: redis
    env: docker
    plan: starter
    image: redis:7 # <-- Use official image!
    port: 6379

  - type: pserv
    name: postgres
    env: docker
    plan: starter
    image: postgres:14 # <-- Use official image!
    envVars:
      - key: POSTGRES_DB
        value: killfile
      - key: POSTGRES_USER
        value: killuser
      - key: POSTGRES_PASSWORD
        value: killpassword
    disks:
      - name: pgdata
        mountPath: /var/lib/postgresql/data
        sizeGB: 10
    port: 5432