services:
  - type: web
    name: kill-file-api
    env: docker
    plan: starter
    dockerfilePath: ./docker/api.Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: MINIO_ENDPOINT
        value: http://minio:9000
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
      - key: MINIO_BUCKET
        value: uploads
    port: 8080

  - type: pserv
    name: minio
    env: docker
    plan: starter
    image: minio/minio:latest
    startCommand: server /data
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
    disks:
      - name: miniodata
        mountPath: /data
        sizeGB: 10
    port: 9000

  - type: pserv
    name: redis
    env: docker
    plan: starter
    image: redis:7
    port: 6379