services:
  - type: web
    name: kill-file-api
    env: docker
    plan: starter
    dockerfilePath: ./docker/api.Dockerfile

  - type: worker
    name: kill-file-worker
    env: docker
    plan: starter
    dockerfilePath: ./docker/worker.Dockerfile