services:
  - type: web
    name: kill-file-api
    env: docker
    plan: starter
    dockerfilePath: ./docker/api.Dockerfile
    envVars:
      - key: REDIS_HOST
        value: <your-redis-service-host>
      - key: MINIO_ENDPOINT
        value: <your-minio-service-url>
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
      - key: MINIO_BUCKET
        value: uploads
    port: 8080

  - type: worker
    name: kill-file-worker
    env: docker
    plan: starter
    dockerfilePath: ./docker/worker.Dockerfile
    envVars:
      - key: REDIS_HOST
        value: <your-redis-service-host>
      - key: MINIO_ENDPOINT
        value: <your-minio-service-url>
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin
      - key: MINIO_BUCKET
        value: uploads